font:
  normal:
    family: OperatorMono Nerd Font
    style: Light 
  bold:
    family: OperatorMono Nerd Font

  italic:
    family: OperatorMono Nerd Font
    style: Light Italic

  bold_italic:
    family: OperatorMono Nerd Font

  size: 26
  offset:
    x: 0
    y: 0



key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }


window:
  opacity: 0.97

  title: Alacritty
schemes:
  ### Doom One ###
  DoomOne: &DoomOne
    primary:
      background: '#141414'
      foreground: '#F5F5F5'
    bright:
      blue:    '#81a2be'
colors: *DoomOne
